/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ProfileIcon() {
  return (
    <div className="flex flex-col self-stretch my-auto w-10">
      <div className="flex flex-col w-10">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/bd5b1b578e56afa2475dd7d42ca33fb250bed4a12e6abf7d8b491a87359afe9f?placeholderIfAbsent=true&apiKey=f2d7e403ce0348a7a99da9027832b54a"
          alt="Profile Icon"
          className="object-contain w-full aspect-square min-h-[40px]"
        />
      </div>
    </div>
  );
}

export default ProfileIcon;
