/**
 * This code was generated by Builder.io.
 */
import React from "react";
import MainContent from "./components/MainContent";

function App() {
  return (
    <div className="App">
      <MainContent />
    </div>
  );
}

export default App;
